### ISSUE TITLE
01. List of images

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#1]
## User Story

As a user I want to have a list of my images, so that I have a great overview of my memories.

## Description (text, scribble, wireframe, design)

![list-images](https://user-images.githubusercontent.com/82401318/120862222-e3065800-c588-11eb-988f-dcd2a875b26a.png)

## Text:
- H1: Viary
- H2: Your memories

## Acceptance criteria

- [x] App Title with H1 Text
- [x] Subtitle with H2 Text
- [x] Unordered list of images
- [x] Images need the same size : 200px * 300px

## Tasks
- [x] Feature branch
- [x] Component w/ storybook and test
- [x] Update App with component

## Complexity (low, medium, high)
low
