### ISSUE TITLE
07. Edit memory

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#10]
## User Story

As a user I want to have the possibility to edit my memory, so that I can correct the text and title.

## Text
No text

## Acceptance criteria
- [x] Edit-Icon on MemorysPage
- [x] Edit text and title
- [x] Show updated text on MemorysPage and DetailMemoryPage

## Tasks
- [x] Feature branch
- [x] Update MemorysPage
- [x] Update DetailMemoryPage
- [x] Update App with component and logic

## Complexity
high
