### ISSUE TITLE
08. HomePage with image-slider

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#13]
## User Story

As a user I want to have a quick overwiev of my memories, so that I see my memories in a stylish way.

## Text
H1: Welcome to your viary - the place for your memories
Button: Enter

## Acceptance criteria
- [x] Add HomePage with H1 and button
- [x] Button-Click leads to CameraPage
- [x] Slider for images

## Tasks
- [x] Feature branch
- [x] Create StartPage with image-slider
- [x] Update App with component and logic

## Complexity
medium
