### ISSUE TITLE
02. Image-view

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#2]
## User Story

As a user I want to have a detailview of an image from my list, so that I can see it better.

## Description (text, scribble, wireframe, design)
![image-view(1)](https://user-images.githubusercontent.com/82401318/120563375-b0cdec80-c408-11eb-8649-2493ea402698.png)

## Text
- [x] H1: Viary
- [x] Button: Your memories

## Acceptance criteria
- [x]  Click of an image open a new screen with image-preview/ detailview
- [x]  Button to get back to the image-list

## Tasks
- [x] Feature branch
- [x] Component w/ storybook and test
- [x] Update App with component and logic

## Complexity
low
