### ISSUE TITLE
03. Camera-access

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#3]
## User Story

As a user I want to have access to my camera, so that I can make my own memories.

## Description (Text, Scribble, Wireframe, Design)
![camera](https://user-images.githubusercontent.com/82401318/120564342-f68bb480-c40a-11eb-8db4-3a72a5608157.png)

## Text

- [x] H1: Viary
- [x] H4: Start your cam

## Acceptance criteria
- [x] Click on camera-button open the camera
- [x] Button "To your memories" leads to screen "Your memories"
- [x] A form with a text-input for image-upload incl. title

## Tasks
- [x] Feature branch
- [x] Component w/ storybook and test
- [x] Update App with component and logic
- [x] API

## Complexity
high
