### ISSUE TITLE
04. Localstorage

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#7]
## User Story

As a user I want to save all my memories, so that I always can see them.

## Text
No text

## Acceptance criteria
- [x] Show memories in a list with title and little pic-preview
- [x] Add localstorage

## Tasks
- [x] Feature branch
- [x] Refine components and MemoryPage
- [x] Update App with component and logic

## Complexity
low
