### ISSUE TITLE
06. Textarea and datepicker

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#8]
## User Story

As a user I want to save my memory with a text and a date, so that I can see it later in my detailview.

## Text
Textarea, placeholder:  Write your experience

## Acceptance criteria
- [x] Add textarea to Camerapage
- [x] Create datepicker  in the form
- [x] Give text and date to DetailMemoryPage

## Tasks
- [x] Feature branch
- [x] Update CameraPage
- [x] Update DetailMemoryPage
- [x] Update App with component and logic

## Complexity
low
