### ISSUE TITLE
05. Delete Memorys

### ISSUE THREAD

**Issue by danicadombek** [danicadombek/capstone-project#9]
## User Story

As a user I want to have the possibility to delete a memory, so that I just have the memorys which I want to have.

## Text
No text

## Acceptance criteria
- [x] Add delete-icon to MemorysPage listitems
- [x] With click on delete-icon the item will removed

## Tasks
- [x] Feature branch
- [x] Update MemoryPage
- [x] Update App with component and logic

## Complexity
high
